CONTIKI_PROJECT = ulbEmbeded
all: $(CONTIKI_PROJECT)

# Do not try to build on Sky because of code size limitation
PLATFORMS_EXCLUDE = sky #z1

PROJECT_SOURCEFILES += protocol.c

CONTIKI = /home/user/contiki-ng
include $(CONTIKI)/Makefile.include



